<h2 style="color: #a8e1e9; border-bottom: 2px solid #3498db; padding-bottom: 5px; margin-top: 20px;">
     Contexte Général du Dataset
</h2>

### Cette dataset de source https://www.data.gov.ma/fr  recense la liste des établissements publics abritant des Classes Préparatoires aux Grandes Écoles (CPGE) au Maroc (mise à jour de juillet 2026). 
### Il contient 32 établissements répartis à travers les différentes régions du Royaume. L'objectif principal de ce projet étant la visualisation

| Colonne | Type | Description / Signification |
| :--- | :--- | :--- |
| **`NOM_ETABL`** | Texte | Nom officiel de l'établissement (Lycée) en français. |
| **`NOM_ETABA`** | Texte | Nom de l'établissement en langue arabe. |
| **`AdresseL`** | Texte | Adresse complète de l'établissement en caractères latins (français). |
| **`AdresseA`** | Texte | Adresse complète de l'établissement en langue arabe. |
| **`LL_COM`** | Texte | Nom de la commune ou de la municipalité d'implantation. |
| **`LL_PROV`** | Texte | Province ou préfecture de rattachement de l'établissement. |
| **`LL_REG`** | Texte | Région administrative du Maroc où se situe l'établissement. |

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px 
import math 
import statistics

In [2]:
dt = pd.read_csv('etablissements_publics_cpge_juillet-2026_fr.csv')

<h2 style="color: #a8e1e9; border-bottom: 2px solid #3498db; padding-bottom: 5px; margin-top: 20px;">
    1. Compréhension des Donnée
</h2>

In [3]:
dt.head()

,NOM_ETABL,NOM_ETABA,AdresseL,AdresseA,LL_COM,LL_PROV,LL_REG
0,Lycée Réda Slaoui,Lycée qualifiant Reda Essaoui,Quartier Sidi Mohamed Agadir,Quartier Sidi Mohammed Agadir,Agadir (Mun.),Préfecture: Agadir-Ida -O,Souss-Massa
1,Lycée Qualifiant Moulay Ismail,Lycée qualifiant Moulay Ismaïl,rue wahhabi ali ben jilali vn meknes,Avenue Al-Wahbi Ali Ben Jilali Ville nouvelle ...,Meknès (Mun.),Préfecture: Meknès,Fès-Meknès
2,Lycée Qualifiant Omar Ibn Al-Khattab,Lycée qualifiant Omar Ibn Al-Khattab,BD ABDELKARIM AL KHATTABI SBATA CMMEKNES,Avenue Abdelkrim El Khattabi Sbata,Meknès (Mun.),Préfecture: Meknès,Fès-Meknès
3,Lycée Qualifiant Technique Mohammed V,Lycée qualifiant Mohammed V technique,BOULEVARD 20 AOUT QUARTIER ATLAS,Avenue 20 Août Quartier Atlas,Béni Mellal (Mun.),Province: Béni Mellal,Béni Mellal-Khénifra
4,Centre des classses préparatoires Ibnou Baja,Centre des classes préparatoires Ibn Baja,BENIMELLAL,Béni Mellal,Béni Mellal (Mun.),Province: Béni Mellal,Béni Mellal-Khénifra

In [4]:
dt.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   NOM_ETABL  32 non-null     str
 1   NOM_ETABA  32 non-null     str
 2   AdresseL   32 non-null     str
 3   AdresseA   32 non-null     str
 4   LL_COM     32 non-null     str
 5   LL_PROV    32 non-null     str
 6   LL_REG     32 non-null     str
dtypes: str(7)
memory usage: 7.1 KB

In [5]:
dt.isnull().sum()

NOM_ETABL    0
NOM_ETABA    0
AdresseL     0
AdresseA     0
LL_COM       0
LL_PROV      0
LL_REG       0
dtype: int64

In [6]:
dt.shape

(32, 7)

In [7]:
dt.describe()

,NOM_ETABL,NOM_ETABA,AdresseL,AdresseA,LL_COM,LL_PROV,LL_REG
count,32,32,32,32,32,32,32
unique,31,31,32,32,26,25,12
top,Lycée Technique,Centre des classes préparatoires,Quartier Sidi Mohamed Agadir,Quartier Sidi Mohammed Agadir,Meknès (Mun.),Préfecture: Meknès,Casablanca-Settat
freq,2,2,1,1,2,2,6

<h2 style="color: #a8e1e9; border-bottom: 2px solid #3498db; padding-bottom: 5px; margin-top: 20px;">
    2. Nettoyage et Préparation (Data Cleaning)
</h2>

### la suppresion des colonnes inutiles

In [8]:
colonne_to_drop = ['NOM_ETABL', 'AdresseL']
dt.drop(columns=colonne_to_drop, inplace=True)

### verification

In [9]:
dt.head(2)

,NOM_ETABA,AdresseA,LL_COM,LL_PROV,LL_REG
0,Lycée qualifiant Reda Essaoui,Quartier Sidi Mohammed Agadir,Agadir (Mun.),Préfecture: Agadir-Ida -O,Souss-Massa
1,Lycée qualifiant Moulay Ismaïl,Avenue Al-Wahbi Ali Ben Jilali Ville nouvelle ...,Meknès (Mun.),Préfecture: Meknès,Fès-Meknès

## traitement de colonne NOM_ETABA

In [10]:
dt['NOM_ETABA'].duplicated().sum()

np.int64(1)

In [11]:
dt['NOM_ETABA'].value_counts().sum()

np.int64(32)

In [12]:
dt['NOM_ETABA'].isnull().sum()

np.int64(0)

In [13]:
dt['NOM_ETABA'].dtype

## traitement de colonne AdresseA

In [14]:
dt['AdresseA'].duplicated().sum()

np.int64(0)

In [15]:
dt['AdresseA'].value_counts().sum()

np.int64(32)

In [16]:
dt['AdresseA'].isnull().sum()

np.int64(0)

In [17]:
dt['AdresseA'].dtype

## traitement de colonne LL_COM

In [18]:
dt['LL_COM'].duplicated().sum()

np.int64(6)

In [19]:
dt['LL_COM'].value_counts().sum()

np.int64(32)

In [20]:
dt['LL_COM'].isnull().sum()

np.int64(0)

## traitement de colonne LL_PROV

In [21]:
dt['LL_PROV'].duplicated().sum()

np.int64(7)

In [22]:
dt['LL_PROV'].value_counts().sum()

np.int64(32)

In [23]:
dt['LL_PROV'].isnull().sum()

np.int64(0)

## traitement de colonne LL_REG

In [24]:
dt['LL_REG'].duplicated().sum()

np.int64(20)

In [25]:
dt['LL_REG'].value_counts().sum()

np.int64(32)

In [26]:
dt['LL_REG'].isnull().sum()

np.int64(0)

In [27]:
dt['LL_REG'].unique()

<ArrowStringArray>
[              'Souss-Massa',                'Fès-Meknès',
      'Béni Mellal-Khénifra',         'Casablanca-Settat',
            'Drâa-Tafilalet',         'Guelmim-Oued Noun',
        'Rabat-Salé-Kénitra',   'Laayoune-Sakia El Hamra',
            'Marrakech-Safi',                  'Oriental',
     'Eddakhla-Oued Eddahab', 'Tanger-Tetouan-Al Hoceima']
Length: 12, dtype: str

In [28]:
dt = dt.rename(columns={
    'NOM_ETABA': 'nom_etablissement',
    'AdresseA': 'adresse',
    'LL_COM': 'commune',
    'LL_PROV': 'province',
    'LL_REG': 'region'
})
dt.head(2)

,nom_etablissement,adresse,commune,province,region
0,Lycée qualifiant Reda Essaoui,Quartier Sidi Mohammed Agadir,Agadir (Mun.),Préfecture: Agadir-Ida -O,Souss-Massa
1,Lycée qualifiant Moulay Ismaïl,Avenue Al-Wahbi Ali Ben Jilali Ville nouvelle ...,Meknès (Mun.),Préfecture: Meknès,Fès-Meknès

# conclusion de partie data cleaning  :
 - en general les colonnes de cette dataset n'ont pas de bruit malgre on observe des duplicates mais on peut pas les conseder comme des duplicates parce que les donnees en relation avec aux et on peut trouver quelque chose differante  
 - chengement des noms des colonne pour bien comprendre

<h2 style="color: #a8e1e9; border-bottom: 2px solid #3498db; padding-bottom: 5px; margin-top: 20px;">
   3. Analyse Exploratoire
</h2>

In [29]:
dt['region'].value_counts()

region
Casablanca-Settat            6
Fès-Meknès                   4
Béni Mellal-Khénifra         4
Rabat-Salé-Kénitra           4
Marrakech-Safi               3
Drâa-Tafilalet               2
Oriental                     2
Eddakhla-Oued Eddahab        2
Tanger-Tetouan-Al Hoceima    2
Souss-Massa                  1
Guelmim-Oued Noun            1
Laayoune-Sakia El Hamra      1
Name: count, dtype: int64

In [30]:
fig = px.bar(dt['region'].value_counts(), 
             x=dt['region'].value_counts().index, 
             y=dt['region'].value_counts().values, 
             color=dt['region'].value_counts().values, 
             labels={'x':'Region', 'y':'Count'}, 
             title='Distribution of CPGE by Region')

fig.update_layout(xaxis_title='le nom de Region ', 
                  yaxis_title='nombre d\'etablissements')

fig.show()

 ### on remarque que la region la plus dominantes c'est casablanca_settat par 6 etablissement, suiver par fes_meknes, beni mellal-khnifra et rabat-sale-kenitra par 4 poue chacune

## la frequence de presence des CPGE par province

In [31]:
dt['province'].value_counts()

province
Préfecture: Meknès           2
Province: Béni Mellal        2
Province: Khouribga          2
Préfecture: Marrakech        2
Province: Oued Ed-Dahab      2
Préfecture: Rabat            2
Province: Settat             2
Préfecture: Agadir-Ida -O    1
Préf. d’Arr. Casablanca A    1
Préf. d’Arr. Al Fida-Mers    1
Province: El Jadida          1
Province: Errachidia         1
Préfecture: Fès              1
Province: Guelmim            1
Province: Kénitra            1
Province: Laâyoune           1
Préfecture: Mohammadia       1
Province: Nador              1
Province: Ouarzazate         1
Préfecture: Oujda-Angad      1
Province: Safi               1
Préfecture: Salé             1
Préfecture: Tanger-Assila    1
Province: Taza               1
Province: Tétouan            1
Name: count, dtype: int64

In [32]:
fig = px.bar(
    dt['province'].value_counts(),
    y=dt['province'].values,
    x=dt['province'].index,
    color=dt['province'],
    orientation='h',
    labels={'x': 'count', 'y': 'province'},
    title='Distribution of CPGE by Province'
)

fig.show()

### Quelles sont les provinces ou préfectures qui possèdent le plus grand nombre de lycées CPGE ?